// Curated list of iconic FIFA soundtrack songs across editions.
// Edit freely — the ranking system uses the `id` to persist ratings.
export const SONGS = [
  { id: "blur-song2", title: "Song 2", artist: "Blur", fifa: "FIFA 98" },
  { id: "fatboy-rockafeller", title: "The Rockafeller Skank", artist: "Fatboy Slim", fifa: "FIFA 99" },
  { id: "robbie-itsonlyus", title: "It's Only Us", artist: "Robbie Williams", fifa: "FIFA 2000" },
  { id: "jamiroquai-littlel", title: "Little L", artist: "Jamiroquai", fifa: "FIFA 2002" },
  { id: "massive-specialcases", title: "Special Cases", artist: "Massive Attack", fifa: "FIFA 2003" },
  { id: "gorillaz-rockthehouse", title: "Rock the House", artist: "Gorillaz", fifa: "FIFA Football 2004" },
  { id: "crystal-borntooslow", title: "Born Too Slow", artist: "The Crystal Method", fifa: "FIFA Football 2004" },
  { id: "franz-thisfire", title: "This Fire", artist: "Franz Ferdinand", fifa: "FIFA 2005" },
  { id: "oasis-lyla", title: "Lyla", artist: "Oasis", fifa: "FIFA 06" },
  { id: "hardfi-hardtobeat", title: "Hard to Beat", artist: "Hard-Fi", fifa: "FIFA 06" },
  { id: "editors-munich", title: "Munich", artist: "Editors", fifa: "FIFA 07" },
  { id: "fratellis-flathead", title: "Flathead", artist: "The Fratellis", fifa: "FIFA 07" },
  { id: "kasabian-shoottherunner", title: "Shoot the Runner", artist: "Kasabian", fifa: "FIFA 08" },
  { id: "mgmt-timetopretend", title: "Time to Pretend", artist: "MGMT", fifa: "FIFA 09" },
  { id: "kingsofleon-crawl", title: "Crawl", artist: "Kings of Leon", fifa: "FIFA 09" },
  { id: "mattkim-daylight", title: "Daylight", artist: "Matt and Kim", fifa: "FIFA 10" },
  { id: "friendlyfires-skeletonboy", title: "Skeleton Boy", artist: "Friendly Fires", fifa: "FIFA 10" },
  { id: "foster-helenabeat", title: "Helena Beat", artist: "Foster the People", fifa: "FIFA 12" },
  { id: "foster-dontstop", title: "Don't Stop (Color on the Walls)", artist: "Foster the People", fifa: "FIFA 12" },
  { id: "kasabian-rewired", title: "Re-Wired", artist: "Kasabian", fifa: "FIFA 12" },
  { id: "madeon-icarus", title: "Icarus", artist: "Madeon", fifa: "FIFA 13" },
  { id: "twodoor-sleepalone", title: "Sleep Alone", artist: "Two Door Cinema Club", fifa: "FIFA 13" },
  { id: "bastille-pompeii", title: "Pompeii", artist: "Bastille", fifa: "FIFA 14" },
  { id: "empire-alive", title: "Alive", artist: "Empire of the Sun", fifa: "FIFA 14" },
  { id: "avicii-thedays", title: "The Days", artist: "Avicii", fifa: "FIFA 15" },
  { id: "knocks-classic", title: "Classic", artist: "The Knocks", fifa: "FIFA 16" },
  { id: "glassanimals-youth", title: "Youth", artist: "Glass Animals", fifa: "FIFA 17" },
  { id: "lorde-homemadedynamite", title: "Homemade Dynamite", artist: "Lorde", fifa: "FIFA 18" },
  { id: "childish-thisisamerica", title: "This Is America", artist: "Childish Gambino", fifa: "FIFA 19" },
  { id: "stormzy-vossibop", title: "Vossi Bop", artist: "Stormzy", fifa: "FIFA 20" },
  { id: "strokes-reptilia", title: "Reptilia", artist: "The Strokes", fifa: "FIFA Football 2004" },
  { id: "thekillers-mrbrightside", title: "Mr. Brightside", artist: "The Killers", fifa: "FIFA 2005" },
  { id: "scissor-takeyoumamaout", title: "Take Your Mama", artist: "Scissor Sisters", fifa: "FIFA 2005" },
  { id: "muse-supermassive", title: "Supermassive Black Hole", artist: "Muse", fifa: "FIFA 07" },
  { id: "vampireweekend-aply", title: "A-Punk", artist: "Vampire Weekend", fifa: "FIFA 09" },
  { id: "lapaz-tenicasluces", title: "Tenía Luces", artist: "La Paz", fifa: "FIFA 10" },
  { id: "phoenix-1901", title: "1901", artist: "Phoenix", fifa: "FIFA 10" },
  { id: "muse-uprising", title: "Uprising", artist: "Muse", fifa: "FIFA 11" },
  { id: "blackkeys-tighten", title: "Tighten Up", artist: "The Black Keys", fifa: "FIFA 11" },
  { id: "thexx-islands", title: "Islands", artist: "The xx", fifa: "FIFA 11" },
  { id: "miike-kidsaint", title: "Kids Aren't Alright", artist: "Miike Snow", fifa: "FIFA 13" },
  { id: "hot-flamingo", title: "Flamingo", artist: "Kero Kero Bonito", fifa: "FIFA 17" },
  { id: "milky-fireinthebarn", title: "Fire in the Barn", artist: "Milky Chance", fifa: "FIFA 17" },
  { id: "wombats-greekt", title: "Greek Tragedy", artist: "The Wombats", fifa: "FIFA 16" },
  { id: "alvarosoler-elmismosol", title: "El Mismo Sol", artist: "Álvaro Soler", fifa: "FIFA 16" },
  { id: "beck-dreams", title: "Dreams", artist: "Beck", fifa: "FIFA 16" },
  { id: "twentyone-stressedout", title: "Stressed Out", artist: "Twenty One Pilots", fifa: "FIFA 16" },
  { id: "alttj-breezeblocks", title: "Breezeblocks", artist: "Alt-J", fifa: "FIFA 13" },
  { id: "kasabian-fastfuse", title: "Fast Fuse", artist: "Kasabian", fifa: "FIFA 10" },
  { id: "lily-ldn", title: "LDN", artist: "Lily Allen", fifa: "FIFA 07" }
];
